version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: rag_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

  app:
    build: .
    container_name: rag_app
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    restart: on-failure

volumes:
  postgres-data: