version: "3"
services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: uvicorn app:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./chroma_data:/chroma/chroma
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - chromadb
